
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABRE_TAG = 2;
  public static final int TEXTO = 12;
  public static final int ATTR_SRC = 11;
  public static final int TAG_A = 8;
  public static final int FECHA_TAG_VAZIA = 4;
  public static final int FECHA_TAG = 3;
  public static final int TAG_IMG = 9;
  public static final int EOF = 0;
  public static final int ATTR_HREF = 10;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int BARRA = 7;
  public static final int ASPAS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABRE_TAG",
  "FECHA_TAG",
  "FECHA_TAG_VAZIA",
  "IGUAL",
  "ASPAS",
  "BARRA",
  "TAG_A",
  "TAG_IMG",
  "ATTR_HREF",
  "ATTR_SRC",
  "TEXTO"
  };
}

